#!/bin/bash
# TerraMISO + Terraform Integration Deployment Script
# This shows how TerraMISO augments traditional Terraform workflows

set -e

echo "🚀 TerraMISO + Terraform Deployment Pipeline"
echo "=============================================="
echo ""

# Step 1: Run TerraMISO AI configuration optimizer
echo "Step 1: Running TerraMISO AI analysis..."
echo "Testing 3 LLM providers to determine optimal Postgres configuration..."
echo ""

python run.py examples/terraform-integration/postgres-config-optimizer.aicl \
  --output-file \
  --experiment-id azure-postgres-optimizer \
  --tags terraform,azure,postgres,production

echo ""
echo "✅ AI analysis complete!"
echo ""

# Step 2: Extract AI-recommended configuration
echo "Step 2: Extracting AI recommendations..."
echo ""

# Parse the final recommendation from TerraMISO output
FINAL_CONFIG=$(cat terraform.tfstate.d/azure-postgres-optimizer.tfstate | \
  jq -r '.resources[] | select(.name == "final_config") | .attributes.content')

echo "AI-selected configuration:"
echo "$FINAL_CONFIG" | jq '.'
echo ""

# Step 3: Generate terraform.tfvars from AI recommendation
echo "Step 3: Generating terraform.tfvars from AI recommendations..."
echo ""

cat > examples/terraform-integration/terraform.tfvars <<EOF
# Auto-generated by TerraMISO AI analysis
# Optimized for: E-commerce workload, 10K DAU, $500/month budget, 99.9% SLA

db_sku_name = $(echo "$FINAL_CONFIG" | jq -r '.terraform_vars.db_sku_name')
db_storage_mb = $(echo "$FINAL_CONFIG" | jq -r '.terraform_vars.db_storage_mb')
backup_retention_days = $(echo "$FINAL_CONFIG" | jq -r '.terraform_vars.backup_retention_days')
geo_redundant_backup = $(echo "$FINAL_CONFIG" | jq -r '.terraform_vars.geo_redundant_backup')

# Admin password (from Azure Key Vault or environment)
admin_password = var.AZURE_POSTGRES_PASSWORD
EOF

echo "Generated terraform.tfvars:"
cat examples/terraform-integration/terraform.tfvars
echo ""

# Step 4: Run Terraform plan with AI-optimized configuration
echo "Step 4: Running Terraform plan..."
echo ""

cd examples/terraform-integration
terraform init
terraform plan -var-file=terraform.tfvars

echo ""
echo "Review the plan above. The configuration was optimized by AI analysis."
echo ""
read -p "Apply this AI-optimized infrastructure? (yes/no): " APPLY

if [ "$APPLY" = "yes" ]; then
  echo ""
  echo "Step 5: Applying Terraform configuration..."
  terraform apply -var-file=terraform.tfvars -auto-approve
  
  echo ""
  echo "✅ Deployment complete!"
  echo ""
  echo "AI Decision Summary:"
  echo "$FINAL_CONFIG" | jq -r '.decision_reasoning'
  echo ""
  echo "Deployed configuration:"
  terraform output optimized_config
else
  echo "Deployment cancelled."
fi

echo ""
echo "🎉 TerraMISO enhanced your Terraform deployment with AI-driven optimization!"
