# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import provider_pb2 as proto_dot_provider__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/provider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProviderStub(object):
    """The Provider service definition.
    This is the universal contract that all tofu-aicl providers (both for
    resource provisioning and for testing/assertions) must implement.
    --- Lifecycle Management ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSchema = channel.unary_unary(
                '/aicl.provider.v1.Provider/GetSchema',
                request_serializer=proto_dot_provider__pb2.GetSchemaRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.GetSchemaResponse.FromString,
                _registered_method=True)
        self.ValidateConfig = channel.unary_unary(
                '/aicl.provider.v1.Provider/ValidateConfig',
                request_serializer=proto_dot_provider__pb2.ValidateConfigRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.ValidateConfigResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/aicl.provider.v1.Provider/Configure',
                request_serializer=proto_dot_provider__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.PlanResourceChange = channel.unary_unary(
                '/aicl.provider.v1.Provider/PlanResourceChange',
                request_serializer=proto_dot_provider__pb2.PlanResourceChangeRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.PlanResourceChangeResponse.FromString,
                _registered_method=True)
        self.ApplyResourceChange = channel.unary_unary(
                '/aicl.provider.v1.Provider/ApplyResourceChange',
                request_serializer=proto_dot_provider__pb2.ApplyResourceChangeRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.ApplyResourceChangeResponse.FromString,
                _registered_method=True)
        self.ReadResource = channel.unary_unary(
                '/aicl.provider.v1.Provider/ReadResource',
                request_serializer=proto_dot_provider__pb2.ReadResourceRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.ReadResourceResponse.FromString,
                _registered_method=True)
        self.DeleteResource = channel.unary_unary(
                '/aicl.provider.v1.Provider/DeleteResource',
                request_serializer=proto_dot_provider__pb2.DeleteResourceRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.DeleteResourceResponse.FromString,
                _registered_method=True)
        self.Execute = channel.unary_stream(
                '/aicl.provider.v1.Provider/Execute',
                request_serializer=proto_dot_provider__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/aicl.provider.v1.Provider/Validate',
                request_serializer=proto_dot_provider__pb2.ValidateRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/aicl.provider.v1.Provider/HealthCheck',
                request_serializer=proto_dot_provider__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=proto_dot_provider__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ProviderServicer(object):
    """The Provider service definition.
    This is the universal contract that all tofu-aicl providers (both for
    resource provisioning and for testing/assertions) must implement.
    --- Lifecycle Management ---
    """

    def GetSchema(self, request, context):
        """GetSchema returns the provider's schema, defining available resources and their attributes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateConfig(self, request, context):
        """ValidateConfig checks if the provider-level configuration is valid.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Configure sets the provider-level configuration (e.g., API keys).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanResourceChange(self, request, context):
        """--- Resource Management (The Terraform-like workflow) ---

        PlanResourceChange previews the changes required to reach the desired state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyResourceChange(self, request, context):
        """ApplyResourceChange creates, updates, or deletes a resource to match the desired configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadResource(self, request, context):
        """ReadResource retrieves the current state of a resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResource(self, request, context):
        """DeleteResource destroys a managed resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """--- AI & Testing Workflow ---

        Execute performs the primary AI action of a resource (e.g., running inference).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """Validate performs assertions against a resource or its output.
        This is the core of the test-cl framework.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """--- Health & Metrics ---

        HealthCheck reports the operational status of the provider container.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSchema,
                    request_deserializer=proto_dot_provider__pb2.GetSchemaRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.GetSchemaResponse.SerializeToString,
            ),
            'ValidateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateConfig,
                    request_deserializer=proto_dot_provider__pb2.ValidateConfigRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.ValidateConfigResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=proto_dot_provider__pb2.ConfigureRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.ConfigureResponse.SerializeToString,
            ),
            'PlanResourceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanResourceChange,
                    request_deserializer=proto_dot_provider__pb2.PlanResourceChangeRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.PlanResourceChangeResponse.SerializeToString,
            ),
            'ApplyResourceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyResourceChange,
                    request_deserializer=proto_dot_provider__pb2.ApplyResourceChangeRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.ApplyResourceChangeResponse.SerializeToString,
            ),
            'ReadResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadResource,
                    request_deserializer=proto_dot_provider__pb2.ReadResourceRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.ReadResourceResponse.SerializeToString,
            ),
            'DeleteResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResource,
                    request_deserializer=proto_dot_provider__pb2.DeleteResourceRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.DeleteResourceResponse.SerializeToString,
            ),
            'Execute': grpc.unary_stream_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=proto_dot_provider__pb2.ExecuteRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.ExecuteResponse.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=proto_dot_provider__pb2.ValidateRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.ValidateResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=proto_dot_provider__pb2.HealthCheckRequest.FromString,
                    response_serializer=proto_dot_provider__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aicl.provider.v1.Provider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aicl.provider.v1.Provider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Provider(object):
    """The Provider service definition.
    This is the universal contract that all tofu-aicl providers (both for
    resource provisioning and for testing/assertions) must implement.
    --- Lifecycle Management ---
    """

    @staticmethod
    def GetSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/GetSchema',
            proto_dot_provider__pb2.GetSchemaRequest.SerializeToString,
            proto_dot_provider__pb2.GetSchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/ValidateConfig',
            proto_dot_provider__pb2.ValidateConfigRequest.SerializeToString,
            proto_dot_provider__pb2.ValidateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/Configure',
            proto_dot_provider__pb2.ConfigureRequest.SerializeToString,
            proto_dot_provider__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlanResourceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/PlanResourceChange',
            proto_dot_provider__pb2.PlanResourceChangeRequest.SerializeToString,
            proto_dot_provider__pb2.PlanResourceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyResourceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/ApplyResourceChange',
            proto_dot_provider__pb2.ApplyResourceChangeRequest.SerializeToString,
            proto_dot_provider__pb2.ApplyResourceChangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/ReadResource',
            proto_dot_provider__pb2.ReadResourceRequest.SerializeToString,
            proto_dot_provider__pb2.ReadResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/DeleteResource',
            proto_dot_provider__pb2.DeleteResourceRequest.SerializeToString,
            proto_dot_provider__pb2.DeleteResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aicl.provider.v1.Provider/Execute',
            proto_dot_provider__pb2.ExecuteRequest.SerializeToString,
            proto_dot_provider__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/Validate',
            proto_dot_provider__pb2.ValidateRequest.SerializeToString,
            proto_dot_provider__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aicl.provider.v1.Provider/HealthCheck',
            proto_dot_provider__pb2.HealthCheckRequest.SerializeToString,
            proto_dot_provider__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)